# Generated by Django 3.1.3 on 2020-11-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordsmodel',
            options={'ordering': ['-id']},
        ),
    ]
