# Generated by Django 3.1.3 on 2020-12-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theNewStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitionsmodel',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='theNewStore.wordmodel', verbose_name='word'),
        ),
    ]
