# Generated by Django 3.1.3 on 2020-12-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theNewStore', '0002_auto_20201206_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel',
            options={'ordering': ['-created_date']},
        ),
    ]
