# Generated by Django 3.1.3 on 2020-12-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theNewStore', '0003_auto_20201206_1715'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wordmodel',
            constraint=models.UniqueConstraint(fields=('word_type',), name='Abdullah this word is exisit already'),
        ),
    ]
