# Generated by Django 3.1.3 on 2020-12-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theNewStore', '0004_auto_20201206_1717'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wordmodel',
            name='Abdullah this word is exisit already',
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='word_text',
            field=models.CharField(help_text='Enter new word', max_length=30, verbose_name='word'),
        ),
        migrations.AddConstraint(
            model_name='wordmodel',
            constraint=models.UniqueConstraint(fields=('word_type',), name='Abdullah this word is exists already'),
        ),
    ]
