# Generated by Django 3.1.3 on 2020-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theNewStore', '0005_auto_20201206_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='word_text',
            field=models.CharField(help_text='Enter new word', max_length=30, unique=True, verbose_name='word'),
        ),
    ]
