# Generated by Django 3.1.3 on 2020-12-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theNewStore', '0006_auto_20201206_1719'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wordmodel',
            name='Abdullah this word is exists already',
        ),
    ]
