# Generated by Django 3.1.3 on 2021-03-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theNewStore', '0007_auto_20201206_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitionsmodel',
            name='definition_text',
            field=models.CharField(help_text="word's definition", max_length=500, verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='example_text',
            field=models.CharField(help_text="word's example", max_length=500, verbose_name='example'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='theNewStore.wordmodel', verbose_name='word'),
        ),
    ]
