# Generated by Django 3.1.3 on 2021-03-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theNewStore', '0008_auto_20210315_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='word_type',
            field=models.CharField(choices=[('v', 'Verb'), ('n', 'Noun'), ('aj', 'Adjective'), ('av', 'Adverb')], default='n', max_length=10, verbose_name='word type'),
        ),
    ]
